import type { SellSideListCandidate, PartialCandidate } from './types'

export const SEED_CANDIDATES: SellSideListCandidate[] = [
  {
    institution: 'Bank of America',
    listName: 'Fab Five Software Stocks for H2 2026',
    displayName: 'Bank of America Fab Five Software Stocks for H2 2026',
    period: 'H2 2026',
    year: 2026,
    theme: 'Infrastructure software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'SNOW', action: 'buy' },
      { ticker: 'DDOG', action: 'buy' },
      { ticker: 'FROG', action: 'buy' },
      { ticker: 'MDB', action: 'buy' },
      { ticker: 'TWLO', action: 'buy' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'Top 10 U.S. Ideas for Q1 2026',
    displayName: 'Bank of America Top 10 U.S. Ideas Q1 2026',
    period: 'Q1 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'BA', action: 'buy' },
      { ticker: 'CI', action: 'buy' },
      { ticker: 'CEG', action: 'buy' },
      { ticker: 'DG', action: 'buy' },
      { ticker: 'EQIX', action: 'buy' },
      { ticker: 'MRK', action: 'buy' },
      { ticker: 'SPOT', action: 'buy' },
      { ticker: 'VRTX', action: 'buy' },
      { ticker: 'LEN', action: 'underperform', note: 'Underperform / non-bullish' },
    ],
  },
  {
    institution: 'Morgan Stanley',
    listName: 'Best Application Software Stocks for 2026',
    displayName: 'Morgan Stanley Best Application Software Stocks for 2026',
    year: 2026,
    sector: 'Application software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'HUBS', action: 'buy' },
      { ticker: 'KVYO', action: 'buy' },
      { ticker: 'WIX', action: 'buy' },
      { ticker: 'AMPL', action: 'buy' },
      { ticker: 'BL', action: 'buy' },
      { ticker: 'DSGX', action: 'buy' },
      { ticker: 'NAVN', action: 'buy' },
    ],
  },
  {
    institution: 'Morgan Stanley',
    listName: 'AI-Hit Software Stocks to Buy on Discount',
    displayName: 'Morgan Stanley AI-Hit Software Stocks to Buy on Discount',
    year: 2026,
    theme: 'AI-hit software rebound',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'MSFT', action: 'buy' },
      { ticker: 'INTU', action: 'buy' },
      { ticker: 'CRM', action: 'buy' },
      { ticker: 'NOW', action: 'buy' },
      { ticker: 'PANW', action: 'buy' },
      { ticker: 'SHOP', action: 'buy' },
      { ticker: 'TEAM', action: 'buy' },
      { ticker: 'NET', action: 'buy' },
      { ticker: 'SNOW', action: 'buy' },
    ],
  },
  {
    institution: 'UBS',
    listName: 'Top 10 Highest-Conviction Stock Picks for 2026',
    displayName: 'UBS Top 10 Highest-Conviction Stock Picks for 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'ACAD', action: 'buy' },
      { ticker: 'LNT', action: 'buy' },
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'AMT', action: 'buy' },
      { ticker: 'COF', action: 'buy' },
      { ticker: 'PEP', action: 'buy' },
      { ticker: 'DECK', action: 'buy' },
      { ticker: 'GM', action: 'buy' },
      { ticker: 'OVV', action: 'buy' },
      { ticker: 'WWD', action: 'buy' },
    ],
  },
  {
    institution: 'UBS',
    listName: '12 Tech, Media, and Telecom High-Conviction Picks',
    displayName: 'UBS 12 Tech, Media, and Telecom High-Conviction Picks',
    year: 2026,
    sector: 'TMT',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'PLTR', action: 'buy' },
      { ticker: 'FROG', action: 'buy' },
      { ticker: 'TWLO', action: 'buy' },
      { ticker: 'ACN', action: 'buy' },
      { ticker: 'NFLX', action: 'buy' },
      { ticker: 'AMT', action: 'buy' },
      { ticker: 'GBTG', action: 'buy' },
      { ticker: 'MA', action: 'buy' },
      { ticker: 'GLBE', action: 'buy' },
      { ticker: 'ENTG', action: 'buy' },
      { ticker: 'ANET', action: 'buy' },
    ],
  },
  {
    institution: 'Citi',
    listName: 'Large Cap Recommended List - 2026 Additions',
    displayName: 'Citi Large Cap Recommended List - 2026 Additions',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'MCHP', action: 'buy' },
      { ticker: 'USB', action: 'buy' },
      { ticker: 'AFRM', action: 'buy' },
      { ticker: 'DAL', action: 'buy' },
      { ticker: 'TMO', action: 'buy' },
      { ticker: 'BA', action: 'buy' },
      { ticker: 'AVGO', action: 'buy' },
      { ticker: 'LIN', action: 'buy' },
      { ticker: 'LRCX', action: 'buy' },
      { ticker: 'MDT', action: 'buy' },
      { ticker: 'FE', action: 'buy' },
    ],
  },
  {
    institution: 'Citi',
    listName: 'Back-Office Software Top Picks',
    displayName: 'Citi Back-Office Software Top Picks',
    period: 'June 2026',
    year: 2026,
    sector: 'Application software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'BOX', action: 'buy' },
      { ticker: 'NAVN', action: 'buy' },
      { ticker: 'APPN', action: 'buy' },
    ],
  },
  {
    institution: 'Jefferies',
    listName: 'Top Software Stocks for 2026',
    displayName: 'Jefferies Top Software Stocks for 2026',
    year: 2026,
    sector: 'Software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'ADP', action: 'buy' },
      { ticker: 'NOW', action: 'buy' },
      { ticker: 'HUBS', action: 'buy' },
      { ticker: 'SHOP', action: 'buy' },
      { ticker: 'TWLO', action: 'buy' },
      { ticker: 'TOST', action: 'buy' },
    ],
  },
  {
    institution: 'BTIG',
    listName: 'TMT Best Picks for 2026',
    displayName: 'BTIG TMT Best Picks for 2026',
    year: 2026,
    sector: 'Technology, Media, Telecom',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'MELI', action: 'buy' },
      { ticker: 'TKO', action: 'buy' },
      { ticker: 'TWLO', action: 'buy' },
      { ticker: 'ZS', action: 'buy' },
      { ticker: 'DKNG', action: 'buy' },
      { ticker: 'U', action: 'buy' },
      { ticker: 'COMP', action: 'buy' },
      { ticker: 'KVYO', action: 'buy' },
    ],
  },
  {
    institution: 'Evercore ISI',
    listName: 'Top 5 Retail Stocks for 2026',
    displayName: 'Evercore ISI Top 5 Retail Stocks for 2026',
    year: 2026,
    sector: 'Retail',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    members: [
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'GPC', action: 'buy' },
      { ticker: 'WMT', action: 'buy' },
      { ticker: 'HD', action: 'buy' },
      { ticker: 'ORLY', action: 'buy' },
    ],
  },
]

export const PARTIAL_CANDIDATES: PartialCandidate[] = [
  {
    institution: 'Goldman Sachs',
    listName: 'Rule of 10 Secular Growth Screen',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 10,
  },
  {
    institution: 'Goldman Sachs',
    listName: 'TMT Conviction List Top Picks',
    year: 2026,
    sector: 'TMT',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
  },
  {
    institution: 'JPMorgan',
    listName: '47 Top Stock Picks for 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 47,
  },
  {
    institution: 'Morgan Stanley',
    listName: '14 Stocks for 4 Themes Defining 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 14,
  },
  {
    institution: 'Oppenheimer',
    listName: 'Best-of-Best 12 SMID Stocks',
    year: 2026,
    sector: 'SMID',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 12,
  },
  {
    institution: 'Piper Sandler',
    listName: '13 Contrarian Consumer Stocks',
    year: 2026,
    sector: 'Consumer',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 13,
  },
]
